# Generated by Django 4.2.10 on 2025-04-09 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('last_completed_level', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=100)),
                ('money', models.IntegerField(default=1000)),
                ('archer_level', models.IntegerField(default=1)),
                ('catapult_level', models.IntegerField(default=1)),
                ('magic_level', models.IntegerField(default=1)),
                ('guardian_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
