# Generated by Django 4.2.10 on 2025-04-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_gameuser_level_remove_gameuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='display_name',
            field=models.CharField(default='Player', max_length=50),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='tutorial_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='money',
            field=models.IntegerField(default=200),
        ),
    ]
