# Generated by Django 4.2.10 on 2025-04-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gameuser_display_name_gameuser_tutorial_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='start_hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='start_money',
            field=models.IntegerField(default=200),
        ),
    ]
