# Generated by Django 4.2.10 on 2025-04-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_gameuser_start_hp_gameuser_start_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='start_hp',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='start_money',
            field=models.IntegerField(default=1),
        ),
    ]
